project = beat_finder
vendor = xilinx
family = spartan3s
part = xc3s100e-tq144
top_module = top
#flashsize = 2048

vfiles = ../rtl/top.v \
		 ../rtl/baud.v  \
		 ../rtl/u_rec.v \
		 ../rtl/u_xmit.v \
		 ../rtl/uart.v

include xilinx.mk
